#ifndef _DC_RENDER_CONSTANTS_DEMOONE_
#define _DC_RENDER_CONSTANTS_DEMOONE_

#include "dcRender.h"

#define RENDER_WIDTH 320
#define RENDER_HEIGHT 240
#define RENDER_BG_COLOR_R 0
#define RENDER_BG_COLOR_G 0
#define RENDER_BG_COLOR_B 0
#define RENDER_ORDER_TABLE_SIZE 4096
#define RENDER_PRIMITIVES_LIST_SIZE 32768
#define RENDER_FONT_CHAR_SIZE 8
#define RENDER_FRAMERATE 50
#endif